import { ClassificationTemplate } from "../schemas.generated.js";
import { Authentication } from "../auth.js";
import { NetworkSession } from "../network.js";
import { Json } from "../json.js";
export type CreateMetadataTemplateSchemaClassificationRequestBodyArgScopeField = "enterprise";
export type CreateMetadataTemplateSchemaClassificationRequestBodyArgTemplateKeyField = "securityClassification-6VMVochwUWo";
export type CreateMetadataTemplateSchemaClassificationRequestBodyArgDisplayNameField = "Classification";
export type CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldTypeField = "enum";
export type CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldKeyField = "Box__Security__Classification__Key";
export type CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldDisplayNameField = "Classification";
export interface CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigFieldClassificationField {
    readonly classificationDefinition?: string;
    readonly colorId?: number;
}
export interface CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigField {
    readonly classification?: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigFieldClassificationField;
}
export interface CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsField {
    readonly key?: string;
    readonly staticConfig?: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigField;
}
export interface CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsField {
    readonly type?: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldTypeField;
    readonly key?: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldKeyField;
    readonly displayName?: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldDisplayNameField;
    readonly hidden?: boolean;
    readonly options?: readonly CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsField[];
}
export interface CreateMetadataTemplateSchemaClassificationRequestBodyArg {
    readonly scope: CreateMetadataTemplateSchemaClassificationRequestBodyArgScopeField;
    readonly templateKey?: CreateMetadataTemplateSchemaClassificationRequestBodyArgTemplateKeyField;
    readonly displayName: CreateMetadataTemplateSchemaClassificationRequestBodyArgDisplayNameField;
    readonly hidden?: boolean;
    readonly copyInstanceOnItemCopy?: boolean;
    readonly fields?: readonly CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsField[];
}
export declare class ClassificationsManager {
    readonly auth?: Authentication;
    readonly networkSession?: NetworkSession;
    constructor(fields: Omit<ClassificationsManager, "getMetadataTemplateEnterpriseSecurityClassificationSchema" | "deleteMetadataTemplateEnterpriseSecurityClassificationSchema" | "createMetadataTemplateSchemaClassification">);
    getMetadataTemplateEnterpriseSecurityClassificationSchema(): Promise<ClassificationTemplate>;
    deleteMetadataTemplateEnterpriseSecurityClassificationSchema(): Promise<any>;
    createMetadataTemplateSchemaClassification(requestBody: CreateMetadataTemplateSchemaClassificationRequestBodyArg): Promise<ClassificationTemplate>;
}
export declare function serializeCreateMetadataTemplateSchemaClassificationRequestBodyArgScopeField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgScopeField): Json;
export declare function deserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgScopeField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgScopeField;
export declare function serializeCreateMetadataTemplateSchemaClassificationRequestBodyArgTemplateKeyField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgTemplateKeyField): Json;
export declare function deserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgTemplateKeyField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgTemplateKeyField;
export declare function serializeCreateMetadataTemplateSchemaClassificationRequestBodyArgDisplayNameField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgDisplayNameField): Json;
export declare function deserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgDisplayNameField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgDisplayNameField;
export declare function serializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldTypeField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldTypeField): Json;
export declare function deserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldTypeField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldTypeField;
export declare function serializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldKeyField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldKeyField): Json;
export declare function deserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldKeyField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldKeyField;
export declare function serializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldDisplayNameField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldDisplayNameField): Json;
export declare function deserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldDisplayNameField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldDisplayNameField;
export declare function serializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigFieldClassificationField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigFieldClassificationField): Json;
export declare function deserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigFieldClassificationField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigFieldClassificationField;
export declare function serializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigField): Json;
export declare function deserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigField;
export declare function serializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsField): Json;
export declare function deserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsField;
export declare function serializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsField): Json;
export declare function deserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsField;
export declare function serializeCreateMetadataTemplateSchemaClassificationRequestBodyArg(val: CreateMetadataTemplateSchemaClassificationRequestBodyArg): Json;
export declare function deserializeCreateMetadataTemplateSchemaClassificationRequestBodyArg(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArg;
