import { ClassificationTemplate } from "../schemas.generated.js";
import { Authentication } from "../auth.js";
import { NetworkSession } from "../network.js";
import { Json } from "../json.js";
export type CreateMetadataTemplateSchemaClassificationRequestBodyArgScopeField = "enterprise";
export type CreateMetadataTemplateSchemaClassificationRequestBodyArgTemplateKeyField = "securityClassification-6VMVochwUWo";
export type CreateMetadataTemplateSchemaClassificationRequestBodyArgDisplayNameField = "Classification";
export type CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldTypeField = "enum";
export type CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldKeyField = "Box__Security__Classification__Key";
export type CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldDisplayNameField = "Classification";
export interface CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigFieldClassificationField {
    readonly classificationDefinition?: string;
    readonly colorId?: number;
}
export interface CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigField {
    readonly classification?: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigFieldClassificationField;
}
export interface CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsField {
    readonly key?: string;
    readonly staticConfig?: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigField;
}
export interface CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsField {
    readonly type?: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldTypeField;
    readonly key?: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldKeyField;
    readonly displayName?: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldDisplayNameField;
    readonly hidden?: boolean;
    readonly options?: readonly CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsField[];
}
export interface CreateMetadataTemplateSchemaClassificationRequestBodyArg {
    readonly scope: CreateMetadataTemplateSchemaClassificationRequestBodyArgScopeField;
    readonly templateKey?: CreateMetadataTemplateSchemaClassificationRequestBodyArgTemplateKeyField;
    readonly displayName: CreateMetadataTemplateSchemaClassificationRequestBodyArgDisplayNameField;
    readonly hidden?: boolean;
    readonly copyInstanceOnItemCopy?: boolean;
    readonly fields?: readonly CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsField[];
}
export declare class ClassificationsManager {
    readonly auth?: Authentication;
    readonly networkSession?: NetworkSession;
    constructor(fields: Omit<ClassificationsManager, "getMetadataTemplateEnterpriseSecurityClassificationSchema" | "deleteMetadataTemplateEnterpriseSecurityClassificationSchema" | "createMetadataTemplateSchemaClassification">);
    getMetadataTemplateEnterpriseSecurityClassificationSchema(): Promise<ClassificationTemplate>;
    deleteMetadataTemplateEnterpriseSecurityClassificationSchema(): Promise<any>;
    createMetadataTemplateSchemaClassification(requestBody: CreateMetadataTemplateSchemaClassificationRequestBodyArg): Promise<ClassificationTemplate>;
}
export declare function newSerializeCreateMetadataTemplateSchemaClassificationRequestBodyArgScopeField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgScopeField): Json;
export declare function newDeserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgScopeField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgScopeField;
export declare function newSerializeCreateMetadataTemplateSchemaClassificationRequestBodyArgTemplateKeyField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgTemplateKeyField): Json;
export declare function newDeserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgTemplateKeyField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgTemplateKeyField;
export declare function newSerializeCreateMetadataTemplateSchemaClassificationRequestBodyArgDisplayNameField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgDisplayNameField): Json;
export declare function newDeserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgDisplayNameField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgDisplayNameField;
export declare function newSerializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldTypeField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldTypeField): Json;
export declare function newDeserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldTypeField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldTypeField;
export declare function newSerializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldKeyField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldKeyField): Json;
export declare function newDeserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldKeyField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldKeyField;
export declare function newSerializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldDisplayNameField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldDisplayNameField): Json;
export declare function newDeserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldDisplayNameField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldDisplayNameField;
export declare function newSerializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigFieldClassificationField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigFieldClassificationField): Json;
export declare function newDeserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigFieldClassificationField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigFieldClassificationField;
export declare function newSerializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigField): Json;
export declare function newDeserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsFieldStaticConfigField;
export declare function newSerializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsField): Json;
export declare function newDeserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsFieldOptionsField;
export declare function newSerializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsField(val: CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsField): Json;
export declare function newDeserializeCreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsField(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArgFieldsField;
export declare function newSerializeCreateMetadataTemplateSchemaClassificationRequestBodyArg(val: CreateMetadataTemplateSchemaClassificationRequestBodyArg): Json;
export declare function newDeserializeCreateMetadataTemplateSchemaClassificationRequestBodyArg(val: any): CreateMetadataTemplateSchemaClassificationRequestBodyArg;
