import { AuthorizationManager } from "./managers/authorization.generated.js";
import { FilesManager } from "./managers/files.generated.js";
import { DownloadsManager } from "./managers/downloads.generated.js";
import { UploadsManager } from "./managers/uploads.generated.js";
import { ChunkedUploadsManager } from "./managers/chunked_uploads.generated.js";
import { ListCollaborationsManager } from "./managers/list_collaborations.generated.js";
import { CommentsManager } from "./managers/comments.generated.js";
import { TasksManager } from "./managers/tasks.generated.js";
import { TrashedFilesManager } from "./managers/trashed_files.generated.js";
import { FileVersionsManager } from "./managers/file_versions.generated.js";
import { FileMetadataManager } from "./managers/file_metadata.generated.js";
import { FileClassificationsManager } from "./managers/file_classifications.generated.js";
import { SkillsManager } from "./managers/skills.generated.js";
import { FileWatermarksManager } from "./managers/file_watermarks.generated.js";
import { FileRequestsManager } from "./managers/file_requests.generated.js";
import { FoldersManager } from "./managers/folders.generated.js";
import { TrashedFoldersManager } from "./managers/trashed_folders.generated.js";
import { FolderMetadataManager } from "./managers/folder_metadata.generated.js";
import { FolderClassificationsManager } from "./managers/folder_classifications.generated.js";
import { TrashedItemsManager } from "./managers/trashed_items.generated.js";
import { FolderWatermarksManager } from "./managers/folder_watermarks.generated.js";
import { FolderLocksManager } from "./managers/folder_locks.generated.js";
import { MetadataTemplatesManager } from "./managers/metadata_templates.generated.js";
import { ClassificationsManager } from "./managers/classifications.generated.js";
import { MetadataCascadePoliciesManager } from "./managers/metadata_cascade_policies.generated.js";
import { SearchManager } from "./managers/search.generated.js";
import { UserCollaborationsManager } from "./managers/user_collaborations.generated.js";
import { TaskAssignmentsManager } from "./managers/task_assignments.generated.js";
import { SharedLinksFilesManager } from "./managers/shared_links_files.generated.js";
import { SharedLinksFoldersManager } from "./managers/shared_links_folders.generated.js";
import { WebLinksManager } from "./managers/web_links.generated.js";
import { TrashedWebLinksManager } from "./managers/trashed_web_links.generated.js";
import { SharedLinksWebLinksManager } from "./managers/shared_links_web_links.generated.js";
import { UsersManager } from "./managers/users.generated.js";
import { SessionTerminationManager } from "./managers/session_termination.generated.js";
import { AvatarsManager } from "./managers/avatars.generated.js";
import { TransferManager } from "./managers/transfer.generated.js";
import { EmailAliasesManager } from "./managers/email_aliases.generated.js";
import { MembershipsManager } from "./managers/memberships.generated.js";
import { InvitesManager } from "./managers/invites.generated.js";
import { GroupsManager } from "./managers/groups.generated.js";
import { WebhooksManager } from "./managers/webhooks.generated.js";
import { EventsManager } from "./managers/events.generated.js";
import { CollectionsManager } from "./managers/collections.generated.js";
import { RecentItemsManager } from "./managers/recent_items.generated.js";
import { RetentionPoliciesManager } from "./managers/retention_policies.generated.js";
import { RetentionPolicyAssignmentsManager } from "./managers/retention_policy_assignments.generated.js";
import { LegalHoldPoliciesManager } from "./managers/legal_hold_policies.generated.js";
import { LegalHoldPolicyAssignmentsManager } from "./managers/legal_hold_policy_assignments.generated.js";
import { FileVersionRetentionsManager } from "./managers/file_version_retentions.generated.js";
import { FileVersionLegalHoldsManager } from "./managers/file_version_legal_holds.generated.js";
import { ShieldInformationBarriersManager } from "./managers/shield_information_barriers.generated.js";
import { ShieldInformationBarrierReportsManager } from "./managers/shield_information_barrier_reports.generated.js";
import { ShieldInformationBarrierSegmentsManager } from "./managers/shield_information_barrier_segments.generated.js";
import { ShieldInformationBarrierSegmentMembersManager } from "./managers/shield_information_barrier_segment_members.generated.js";
import { ShieldInformationBarrierSegmentRestrictionsManager } from "./managers/shield_information_barrier_segment_restrictions.generated.js";
import { DevicePinnersManager } from "./managers/device_pinners.generated.js";
import { TermsOfServicesManager } from "./managers/terms_of_services.generated.js";
import { TermsOfServiceUserStatusesManager } from "./managers/terms_of_service_user_statuses.generated.js";
import { CollaborationAllowlistEntriesManager } from "./managers/collaboration_allowlist_entries.generated.js";
import { CollaborationAllowlistExemptTargetsManager } from "./managers/collaboration_allowlist_exempt_targets.generated.js";
import { StoragePoliciesManager } from "./managers/storage_policies.generated.js";
import { StoragePolicyAssignmentsManager } from "./managers/storage_policy_assignments.generated.js";
import { ZipDownloadsManager } from "./managers/zip_downloads.generated.js";
import { SignRequestsManager } from "./managers/sign_requests.generated.js";
import { WorkflowsManager } from "./managers/workflows.generated.js";
import { DeveloperTokenAuth } from "./developerTokenAuth.js";
import { CCGAuth } from "./ccgAuth.js";
export type ClientAuthField = DeveloperTokenAuth | CCGAuth;
export declare class Client {
    readonly auth: ClientAuthField;
    readonly authorization: AuthorizationManager;
    readonly files: FilesManager;
    readonly downloads: DownloadsManager;
    readonly uploads: UploadsManager;
    readonly chunkedUploads: ChunkedUploadsManager;
    readonly listCollaborations: ListCollaborationsManager;
    readonly comments: CommentsManager;
    readonly tasks: TasksManager;
    readonly trashedFiles: TrashedFilesManager;
    readonly fileVersions: FileVersionsManager;
    readonly fileMetadata: FileMetadataManager;
    readonly fileClassifications: FileClassificationsManager;
    readonly skills: SkillsManager;
    readonly fileWatermarks: FileWatermarksManager;
    readonly fileRequests: FileRequestsManager;
    readonly folders: FoldersManager;
    readonly trashedFolders: TrashedFoldersManager;
    readonly folderMetadata: FolderMetadataManager;
    readonly folderClassifications: FolderClassificationsManager;
    readonly trashedItems: TrashedItemsManager;
    readonly folderWatermarks: FolderWatermarksManager;
    readonly folderLocks: FolderLocksManager;
    readonly metadataTemplates: MetadataTemplatesManager;
    readonly classifications: ClassificationsManager;
    readonly metadataCascadePolicies: MetadataCascadePoliciesManager;
    readonly search: SearchManager;
    readonly userCollaborations: UserCollaborationsManager;
    readonly taskAssignments: TaskAssignmentsManager;
    readonly sharedLinksFiles: SharedLinksFilesManager;
    readonly sharedLinksFolders: SharedLinksFoldersManager;
    readonly webLinks: WebLinksManager;
    readonly trashedWebLinks: TrashedWebLinksManager;
    readonly sharedLinksWebLinks: SharedLinksWebLinksManager;
    readonly users: UsersManager;
    readonly sessionTermination: SessionTerminationManager;
    readonly avatars: AvatarsManager;
    readonly transfer: TransferManager;
    readonly emailAliases: EmailAliasesManager;
    readonly memberships: MembershipsManager;
    readonly invites: InvitesManager;
    readonly groups: GroupsManager;
    readonly webhooks: WebhooksManager;
    readonly events: EventsManager;
    readonly collections: CollectionsManager;
    readonly recentItems: RecentItemsManager;
    readonly retentionPolicies: RetentionPoliciesManager;
    readonly retentionPolicyAssignments: RetentionPolicyAssignmentsManager;
    readonly legalHoldPolicies: LegalHoldPoliciesManager;
    readonly legalHoldPolicyAssignments: LegalHoldPolicyAssignmentsManager;
    readonly fileVersionRetentions: FileVersionRetentionsManager;
    readonly fileVersionLegalHolds: FileVersionLegalHoldsManager;
    readonly shieldInformationBarriers: ShieldInformationBarriersManager;
    readonly shieldInformationBarrierReports: ShieldInformationBarrierReportsManager;
    readonly shieldInformationBarrierSegments: ShieldInformationBarrierSegmentsManager;
    readonly shieldInformationBarrierSegmentMembers: ShieldInformationBarrierSegmentMembersManager;
    readonly shieldInformationBarrierSegmentRestrictions: ShieldInformationBarrierSegmentRestrictionsManager;
    readonly devicePinners: DevicePinnersManager;
    readonly termsOfServices: TermsOfServicesManager;
    readonly termsOfServiceUserStatuses: TermsOfServiceUserStatusesManager;
    readonly collaborationAllowlistEntries: CollaborationAllowlistEntriesManager;
    readonly collaborationAllowlistExemptTargets: CollaborationAllowlistExemptTargetsManager;
    readonly storagePolicies: StoragePoliciesManager;
    readonly storagePolicyAssignments: StoragePolicyAssignmentsManager;
    readonly zipDownloads: ZipDownloadsManager;
    readonly signRequests: SignRequestsManager;
    readonly workflows: WorkflowsManager;
    constructor(fields: Omit<Client, "authorization" | "files" | "downloads" | "uploads" | "chunkedUploads" | "listCollaborations" | "comments" | "tasks" | "trashedFiles" | "fileVersions" | "fileMetadata" | "fileClassifications" | "skills" | "fileWatermarks" | "fileRequests" | "folders" | "trashedFolders" | "folderMetadata" | "folderClassifications" | "trashedItems" | "folderWatermarks" | "folderLocks" | "metadataTemplates" | "classifications" | "metadataCascadePolicies" | "search" | "userCollaborations" | "taskAssignments" | "sharedLinksFiles" | "sharedLinksFolders" | "webLinks" | "trashedWebLinks" | "sharedLinksWebLinks" | "users" | "sessionTermination" | "avatars" | "transfer" | "emailAliases" | "memberships" | "invites" | "groups" | "webhooks" | "events" | "collections" | "recentItems" | "retentionPolicies" | "retentionPolicyAssignments" | "legalHoldPolicies" | "legalHoldPolicyAssignments" | "fileVersionRetentions" | "fileVersionLegalHolds" | "shieldInformationBarriers" | "shieldInformationBarrierReports" | "shieldInformationBarrierSegments" | "shieldInformationBarrierSegmentMembers" | "shieldInformationBarrierSegmentRestrictions" | "devicePinners" | "termsOfServices" | "termsOfServiceUserStatuses" | "collaborationAllowlistEntries" | "collaborationAllowlistExemptTargets" | "storagePolicies" | "storagePolicyAssignments" | "zipDownloads" | "signRequests" | "workflows">);
}
