import { ClassificationTemplateInput } from '../schemas/classificationTemplate.generated.js';
import { BoxClientInput } from '../client.generated.js';
import { FolderFull } from '../schemas/folderFull.generated.js';
import { ClassificationTemplateFieldsOptionsField } from '../schemas/classificationTemplate.generated.js';
import { ShieldInformationBarrier } from '../schemas/shieldInformationBarrier.generated.js';
import { BoxClient } from '../client.generated.js';
import { ClassificationTemplate } from '../schemas/classificationTemplate.generated.js';
import { FileFull } from '../schemas/fileFull.generated.js';
import { TermsOfService } from '../schemas/termsOfService.generated.js';
import { BoxCcgAuth } from '../box/ccgAuth.generated.js';
import { BoxJwtAuth } from '../box/jwtAuth.generated.js';
export declare function getCcgAuth(): BoxCcgAuth;
export declare function getJwtAuth(): BoxJwtAuth;
export declare function getDefaultClientWithUserSubject(userId: string): BoxClient;
export declare function getDefaultClient(): BoxClient;
export declare function createNewFolder(): Promise<FolderFull>;
export declare function uploadNewFile(): Promise<FileFull>;
export declare function getOrCreateTermsOfServices(): Promise<TermsOfService>;
export declare function getOrCreateClassification(classificationTemplateInput: ClassificationTemplateInput): Promise<ClassificationTemplateFieldsOptionsField>;
export declare function getOrCreateClassificationTemplate(): Promise<ClassificationTemplate>;
export declare function getOrCreateShieldInformationBarrier(clientInput: BoxClientInput, enterpriseId: string): Promise<ShieldInformationBarrier>;
//# sourceMappingURL=commons.generated.d.ts.map