name: build-and-test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    name: Browser ${{ matrix.browser }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Run tests
        run: |
          cd test-browser
          npm install
          npx start-server-and-test build-run 3000 'cypress run --browser ${{ matrix.browser }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JWT_CONFIG_BASE_64: ${{ secrets.JWT_CONFIG_BASE_64 }}
          ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USER_ID: ${{ secrets.USER_ID }}
          ENTERPRISE_ID: ${{ secrets.ENTERPRISE_ID }}
          BOX_FILE_REQUEST_ID: ${{ secrets.BOX_FILE_REQUEST_ID }}
          BOX_EXTERNAL_USER_EMAIL: ${{ secrets.BOX_EXTERNAL_USER_EMAIL }}
          WORKFLOW_FOLDER_ID: ${{ secrets.WORKFLOW_FOLDER_ID }}
          APP_ITEM_ASSOCIATION_FILE_ID: ${{ secrets.APP_ITEM_ASSOCIATION_FILE_ID }}
          APP_ITEM_ASSOCIATION_FOLDER_ID: ${{ secrets.APP_ITEM_ASSOCIATION_FOLDER_ID }}
          APP_ITEM_SHARED_LINK: ${{ secrets.APP_ITEM_SHARED_LINK }}
          SLACK_AUTOMATION_USER_ID: ${{ secrets.SLACK_AUTOMATION_USER_ID }}
          SLACK_ORG_ID: ${{ secrets.SLACK_ORG_ID }}
          SLACK_PARTNER_ITEM_ID: ${{ secrets.SLACK_PARTNER_ITEM_ID }}
